### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by SGShen** [chainer/onnx-chainer#10]
Hello, The step in installation "pip install git+git://github.com/onnx/onnx.git@8d0fc40162e0df1d14a0eba9e9696568153e54fd" gave out "Connection Timeout" error message.  Could you give it a fix? Thanks!

**Comment by mitmul** [comment]
@SGShen That seems not the problem of this repository. Could you ask it in the issue of [onnx/onnx](https://github.com/onnx/onnx) repository?

**Comment by disktnk** [comment]
ONNX module supported by ONNX-Chainer is updated, please upgrade it. We close this issue but feel free to make new issue when having a trouble on installation.
