### ISSUE TITLE
OneHot is not implemented in onnxruntime==0.2.1

### ISSUE THREAD

**Issue by ir5** [chainer/onnx-chainer#108]
It seems like `OneHot` node is not supported in the latest version of `onnxruntime==0.2.1`.
This prevents from performing a test for `SoftmaxCrossEntropy` function node in https://github.com/chainer/onnx-chainer/pull/107.

**Comment by disktnk** [comment]
ONNXRuntime 0.4.0 has already implemented OneHot op, but not supported int32 input, reported https://github.com/microsoft/onnxruntime/issues/1537

**Comment by disktnk** [comment]
fixed by https://github.com/chainer/chainer/pull/8347 and back ported.
