### ISSUE TITLE
Support chainer.links.Bias

### ISSUE THREAD

**Issue by believeitmyway** [chainer/onnx-chainer#146]
chainer.links.Bias is not included in Supported Functions.
However, I can export onnx model including Bias function.

Is chainer.links.Bias officially supported?
If the answer is YES, can you update Supported Functions?

**Comment by believeitmyway** [comment]
Sorry, my comment is not correct.
I visualize the onnx model.
But Bias function is not included.

chainer.links.Bias is not supported now, right?

**Comment by disktnk** [comment]
Chainer breaks `Bias` function down to `Reshape`, `BroadcastTo` and `Add` function node https://github.com/chainer/chainer/blob/v5.4.0/chainer/functions/math/bias.py#L46-L48

ONNX-Chainer converts these broken down function nodes to ONNX operators.

Example:

```python
class Model(chainer.Chain):
    def __init__(self):
        super(Model, self).__init__()
        with self.init_scope():
            self.bias = L.Bias()
    def __call__(self, x, y):
        return self.bias(x, y)
```

```python
x = np.zeros((1,2,3,4))
y = np.zeros((2,3))
export(Model(), (x, y))
```

This `Model` will be exported as

![image](https://user-images.githubusercontent.com/414255/56267035-a537e280-6128-11e9-9199-3527c2320f9d.png)

If your ONNX graph looks similar to the above image, it's Chainer and ONNX-Chainer specification.

**Comment by believeitmyway** [comment]
Thank you!
I understand ONNX-Chainer specification.
