### ISSUE TITLE
Does onnx support L.DepthwiseConvolution2D?

### ISSUE THREAD

**Issue by sharpstill** [chainer/onnx-chainer#17]
I am reproduce tensorflow mobilenet to chainer version
But it use L.DepthwiseConvolution2D.  I want to translate their pretrained model to chainer use.
How to do that ?
mobilenet code is here:
https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.py

**Comment by disktnk** [comment]
Sorry for late reply.

`F.depthwise_convolution_2d` is represented by `Transpose` + `Reshape` + `Conv2D` [source](https://github.com/chainer/chainer/blob/v6.2.0/chainer/functions/connection/depthwise_convolution_2d.py), so current ONNX-Chainer can export them.

```
class Model(chainer.Chain):

    def __init__(self):
        super(Model, self).__init__()
        with self.init_scope():
            self.dwc = L.DepthwiseConvolution2D(3, 2, 2)

    def forward(self, x):
        return self.dwc(x)

x = ...
export(Model(), x, train=True)
```

![image](https://user-images.githubusercontent.com/414255/62269584-80187700-b46e-11e9-8a43-15e33670b335.png)
