### ISSUE TITLE
Cannot get Dockerfile to work

### ISSUE THREAD

**Issue by sennendoko** [chainer/onnx-chainer#20]
Hi, I think onnx-chainer/docker/Dockerfile may have got a bit out of date because of various dependencies. I am running Ubuntu 16.04.3.

(1) The first problem is that the git clone of caffe2 does not work:

```
Step 30/45 : RUN git clone --recursive https://github.com/caffe2/caffe2.git $HOME/caffe2
 ---> Running in 18857916b52b
Cloning into '/root/caffe2'...
  [several Submodules are registered and paths are checked out OK, then:]
Cloning into 'third_party/aten'...
fatal: reference is not a tree: f3c627d517968c20e8269ead1d90cd3a6c199356
```

and then:
```
Cloning into 'third_party/eigen'...
fatal: could not read Username for 'https://github.com': No such device or address
Clone of 'https://github.com/RLovelett/eigen.git' into submodule path 'third_party/eigen' failed
The command '/bin/sh -c git clone --recursive https://github.com/caffe2/caffe2.git $HOME/caffe2' returned a non-zero code: 1
```
(2) If I take out the caffe2 section (the lines from "RUN git clone ...caffe2" to "RUN pip install onnx-caffe2==1.0.0" inclusive) then I get a similar problem from the mxnet section.

(3) If I take out all the parts that install other frameworks than chainer, i.e. I delete from "RUN git clone ...caffe2" to the end of the file, I can build an image OK, but I can't get it to find the onnx_chainer package:
```
docker run -it <my_image>
root@285853fd7e4c:/# which python
/miniconda/bin/python
root@285853fd7e4c:/# python
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chainer
>>> import onnx
>>> import onnx_chainer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'onnx_chainer'
>>>
root@285853fd7e4c:/# find / -name '*onnx_chainer*'
<no result>
```
Would it be possible (instead, or additionally) to provide a Dockerfile that adds onnx support to something in the chainer/chainer Docker repo?

Thanks

**Comment by mitmul** [comment]
Sorry for the inconvenience, I’ll update this repo in this weekend to support newer version of ONNX, then will update Dockerfile soon.

**Comment by mitmul** [comment]
@sennendoko The latest version of ONNX-Chainer is tested with MXNet and NNVM, so that Caffe2 is no longer needed. I removed those part from Dockerfile. I ensured that the current [Dockerfile](https://github.com/chainer/onnx-chainer/blob/master/docker/Dockerfile) can be successfully built. Please try it instead of the old one.
