### ISSUE TITLE
Buid docker errors

### ISSUE THREAD

**Issue by passionguan** [chainer/onnx-chainer#26]
Hi, I have faced several build docker errors when using the command "bash build_docker.sh" on Ubuntu 16.04, with onnx 1.1.1, Chainer 3.5.0, and Python 2.7. The errors are attached as follows, can you please help me solve these errors as soon as possible? Many thanks for that!

[ 13%] Building CXX object CMakeFiles/tvm.dir/src/arithmetic/bound_deducer.cc.o
[ 14%] Building CXX object CMakeFiles/tvm.dir/src/arithmetic/canonical.cc.o
/root/tvm/src/api/dsl_api.cc: In member function 'virtual void tvm::runtime::DSLAPIImpl::NodeGetAttr(NodeHandle, const char*, TVMValue*, int*, int*) const':
/root/tvm/src/api/dsl_api.cc:123:19: error: cannot declare variable 'getter' to be of abstract type 'tvm::runtime::APIAttrGetter'
     APIAttrGetter getter;
                   ^
/root/tvm/src/api/dsl_api.cc:32:8: note:   because the following virtual functions are pure within 'tvm::runtime::APIAttrGetter':
 struct APIAttrGetter : public AttrVisitor {
        ^
In file included from /root/tvm/include/tvm/./base.h:11:0,
                 from /root/tvm/include/tvm/api_registry.h:10,
                 from /root/tvm/src/api/dsl_api.cc:9:
/root/tvm/HalideIR/src/tvm/node.h:43:16: note: 	virtual void tvm::AttrVisitor::Visit(const char*, tvm::runtime::NDArray*)
   virtual void Visit(const char* key, runtime::NDArray* value) = 0;
                ^
/root/tvm/src/api/dsl_api.cc: In member function 'virtual void tvm::runtime::DSLAPIImpl::NodeListAttrNames(NodeHandle, int*, const char***) const':
/root/tvm/src/api/dsl_api.cc:151:16: error: cannot declare variable 'dir' to be of abstract type 'tvm::runtime::APIAttrDir'
     APIAttrDir dir;
                ^
/root/tvm/src/api/dsl_api.cc:71:8: note:   because the following virtual functions are pure within 'tvm::runtime::APIAttrDir':
 struct APIAttrDir : public AttrVisitor {
        ^
In file included from /root/tvm/include/tvm/./base.h:11:0,
                 from /root/tvm/include/tvm/api_registry.h:10,
                 from /root/tvm/src/api/dsl_api.cc:9:
/root/tvm/HalideIR/src/tvm/node.h:43:16: note: 	virtual void tvm::AttrVisitor::Visit(const char*, tvm::runtime::NDArray*)
   virtual void Visit(const char* key, runtime::NDArray* value) = 0;
                ^
CMakeFiles/tvm.dir/build.make:153: recipe for target 'CMakeFiles/tvm.dir/src/api/dsl_api.cc.o' failed
make[2]: *** [CMakeFiles/tvm.dir/src/api/dsl_api.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 15%] Linking CXX shared library libtvm_runtime.so
[ 15%] Built target tvm_runtime
make[1]: *** [CMakeFiles/tvm.dir/all] Error 2
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/tvm.dir/all' failed
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c cd $HOME/tvm && git checkout ${TVM_COMMIT_ID} &&     mkdir build && cd build     && cmake -DUSE_LLVM=ON ..     && make -j$(nproc) install' returned a non-zero code: 2
The push refers to repository [docker.io/mitmul/onnx-chainer]
An image does not exist locally with the tag: mitmul/onnx-chainer

**Comment by passionguan** [comment]
UPDATE: I used the ONNX 1.1.2.

**Comment by mitmul** [comment]
@passionguan I ensured that the current [Dockerfile](https://github.com/chainer/onnx-chainer/blob/master/docker/Dockerfile) can be successfully built. Please try the latest one. Thanks.
