### ISSUE TITLE
To merge with the mainstream Chainer

### ISSUE THREAD

**Issue by mitmul** [chainer/onnx-chainer#48]
- [x] Add `input_names` and `output_names` options to the `export` function
- [ ] Add `force_export` option to `export` function to make auto-renaming of nodes possible
- [ ] Add `custom_name_resolver` option to `export` function for custom renaming by users
- [x] Fix all source files to pass flake8 + hacking checks

**Comment by disktnk** [comment]
https://github.com/chainer/chainer/pull/8229

**Comment by disktnk** [comment]
merged!, so close this issue.
