### ISSUE TITLE
cannot broadcast a non-scalar to a scalar array?

### ISSUE THREAD

**Issue by lxy5513** [chainer/onnx-chainer#53]
Hi, I have a problem in export model to ONNX, could you help me? as follow:
In program, it works,
![image](https://user-images.githubusercontent.com/39720528/50136057-740de980-02d1-11e9-94a6-5b527c75da5a.png)
however, when In `ONNXExport(opset_version)` context, it occur problems
![image](https://user-images.githubusercontent.com/39720528/50136189-e4b50600-02d1-11e9-95b2-f22e77378d43.png)

could you tell how to fix it, thanks a lot

**Comment by mitmul** [comment]
@lxy5513 Could you provide the whole code to reproduce the problem? What the model is doing in its `__call__` method or `forward` method? And what are the inputs (`y0`, `y1`, ..., `y7`) to the model? The information to investigate the problem is not enough.

**Comment by lxy5513** [comment]
Sorry,It's my fault, I have already fixed it
