### ISSUE TITLE
export error about BroadCastTo

### ISSUE THREAD

**Issue by k5iogura** [chainer/onnx-chainer#86]
I'm trying export OurModel via onnx-chainer 1.4.1 from pip3.
OurModel uses F.reshape and F.transpose instead of Darknet reorg layer function.
I got error message bellow,
---from here
Traceback (most recent call last):
    onnx_chainer.export(ourmodel, x_data ,filename='ourmodel.onnx', opset_version=None)
  File "$HOME/.local/lib/python3.5/site-packages/onnx_chainer/export.py", line 266, in export
    outputs.backward()
  File "$HOME/.local/lib/python3.5/site-packages/chainer/variable.py", line 963, in backward
    self._backward_main(retain_grad, loss_scale)
  File "$HOME/.local/lib/python3.5/site-packages/chainer/variable.py", line 1043, in _backward_main
    hook.backward_postprocess(func, in_data, out_grad_array)
  File "$HOME/.local/lib/python3.5/site-packages/onnx_chainer/export.py", line 128, in backward_postprocess
    onnx_op_name, opset_versions = mapping.operators[func_name]
KeyError: 'BroadcastTo'
--- end of message

OurModel don't use 'BroadcastTo' layer, but onnx-chainer select it for OurModel. I don't know why.
And I don't understand why to use cuda modules even though i do not using GPU.
A part of OurModel corresponding to reorg layer bellow,

---from here code snipet
batch_size, input_channel, input_height, input_width = h.data.shape
output_height, output_width, output_channel = int(input_height/2), int(input_width/2), input_channel*2*2
output = F.transpose(F.reshape(h, (batch_size, input_channel, output_height, 2, output_width, 2)), (0, 1, 2, 4, 3, 5))
output = F.transpose(F.reshape(output, (batch_size, input_channel, output_height, output_width, -1)), (0, 4, 1, 2, 3))
high_resolution_feature = F.reshape(output, (batch_size, output_channel, output_height, output_width))
--- end of a code snipet

onn-chainer opset_verson is latest(specified None), may be opset_version >= 7.
Please help me anyone.

**Comment by disktnk** [comment]
I'm not familiar with "Darknet reorg layer" (is it related to YOLOv2?), `chainer.functions.broadcast_to` is used in various functions. For example, `chainer.links.Bias` calls `broadcast_to` internally. Unfortunately `BroadcastTo` function does not supported in current ONNX-Chainer.

`BroadcastTo` can be converted as `Expand` operator, added from opset 8, so may be able to support the function, but we need to survey more detail difference between `BroadcastTo` and `Expand`, and fix tests (especially minimal version of opset).

**Comment by k5iogura** [comment]
Thanks for your information.
Just to confirm, onnx_chainer.export outputs "broadcast_to" but current onnx-chainer don't support it?
In error message, 
  onnx_op_name, opset_versions = mapping.operators[func_name]
at this point strings variable func_name has value "BroadcastTo". 
onnx-chainer generates "BroadcatTo" by itself, and onnx-chainer say "i don't know it" ?

So, let me know how to make generated "expand" instead of "broadcast_to" or how to write chainer network definition script.
Best Regards.

**Comment by disktnk** [comment]
> onnx_chainer.export outputs "broadcast_to" but current onnx-chainer don't support it?

ONNX-Chainer's `export` does not generate `BroadcastTo` function itself, `export` calls model running like `outputs = model(*inputs)` internally to get `FunctionNode`s, outputs. then makes ONNX graph.

It's point to note that `FunctionNode`s don't match with models definition. If the model includes `chainer.links.Bias`, for example, Chainer breaks down the `Bias` to `BroadcastTo` and other `FunctionNode`. ONNX-Chainer have to convert `BroadcastTo` `FunctionNode` but currently does not support it.

> how to make generated "expand" instead of "broadcast_to" or how to write chainer network definition script.

Need to modify ONNX-Chainer's source code, ref #87

**Comment by k5iogura** [comment]
Thank you very much for good information, i understood.  
To avoid using Bias layer in chainer network definition, i used batchnormalize beta option instead of Bias layer and it look like work fine.  

Best regards.

**Comment by disktnk** [comment]
`BroadcastTo` will be supported next release
